# Generated by Django 5.2.13 on 2026-05-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0002_alter_userprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, max_length=1048576, null=True, upload_to="profile_images/"
            ),
        ),
    ]
